# Generated by Django 4.0 on 2025-02-03 15:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=124, null=True)),
                ("last_name", models.CharField(blank=True, max_length=124, null=True)),
                ("address_line_1", models.CharField(blank=True, max_length=255, null=True)),
                ("address_line_2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=124, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Billing address",
                "verbose_name_plural": "Billing address",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("brand", models.CharField(max_length=128)),
                ("exp_month", models.IntegerField()),
                ("exp_year", models.IntegerField()),
                ("last4", models.CharField(max_length=4)),
                ("payment_method_id", models.CharField(max_length=128, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "invoice_id",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("credits_applied", models.IntegerField(default=0)),
                ("discount", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                ("issued_date", models.DateField()),
                ("issued", models.DateTimeField()),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Failed"),
                            (1, "Paid"),
                            (2, "Pending"),
                            (3, "Canceled"),
                            (4, "Scheduled"),
                            (5, "Canceling Scheduled"),
                            (6, "Trial"),
                        ],
                        default=0,
                    ),
                ),
            ],
            options={
                "ordering": ("-issued",),
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(blank=True, max_length=256, null=True)),
                ("price", models.IntegerField(default=0)),
                ("discount", models.IntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="payments.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
