# Generated by Django 4.0 on 2025-02-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0002_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cards",
                to="user.country",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="card",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_billing",
                to="payments.card",
            ),
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="country",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="users_address",
                to="user.country",
            ),
        ),
    ]
