upstream web_app_upstream {
   server django:8000;
}

server {
   listen 80;
   server_name inhouseapp.dataforest.tech;
   client_max_body_size 1024M;
   location /.well-known/acme-challenge/ {
       root /var/www/certbot;
   }
   location / {
       proxy_read_timeout 1800;
       proxy_connect_timeout 1800;
       proxy_send_timeout 1800;
       send_timeout 1800;
       return 301 https://$host$request_uri;
   }
}

server {
   listen 443 ssl;
   server_name inhouseapp.dataforest.tech;
   client_max_body_size 1024M;
   ssl_certificate /etc/letsencrypt/live/inhouseapp.dataforest.tech/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/inhouseapp.dataforest.tech/privkey.pem;
   include /etc/letsencrypt/options-ssl-nginx.conf;
   ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

   location / {
       root /srv/www/web_app/frontend_build; # new line added
       try_files $uri $uri/ /index.html; # new
       index index.html index.htm; # new line added
   }    

   location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

   location /api/ {
       proxy_pass http://web_app_upstream;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto https;
       proxy_set_header Host $host;
       proxy_redirect off;
   }
}
