"""
Django settings for InHome project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os


# Production or Development settings
IS_PRODUCTION = os.environ["IS_PRODUCTION"].lower() in ('true', '1', 't')
IS_LOCAL = os.environ["IS_LOCAL"].lower() in ('true', '1', 't')

ONBOARDING_ENABLED = os.environ["ONBOARDING_ENABLED"].lower() in ('true', '1', 't')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*', 'localhost', 'localhost:8001', '127.0.0.1', '0.0.0.0', '192.168.10.151', '192.168.10.151:8001', 'inhouseapp.dataforest.tech']
INTERNAL_IPS = ALLOWED_HOSTS

AUTH_USER_MODEL = 'user.User'


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3th party app
    'modeltranslation',
    'corsheaders',
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_cleanup.apps.CleanupConfig',
    'django.contrib.postgres',
    # 'drf_yasg',   # need for swagger ui
    # 'django-storages',    # need for connecting AWS S3 Bucket for static and media files collecting

    # Local applications
    'core',
    'admin_panel',
    'authentication',
    'user',
    'subscription',
    'dashboard',
    "payments",

]


SOCIAL_AUTH_AUTHENTICATION_BACKENDS = (
    'social_core.backends.apple.AppleIdAuth',
)

MIDDLEWARE = [
    'core.middleware.DecryptingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'core.middleware.LangBasedOnUserSettingsMiddleware',   # custom middleware for detecting language from user profile
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RequestLogMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'core.auth.CustomJWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    'PAGE_SIZE': 20,
    'SEARCH_PARAM': 'q',
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'EXCEPTION_HANDLER': 'core.error_handler.rest_framework_custom_exception_handler'
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),

    'ROTATE_REFRESH_TOKENS': True,

    'USER_AUTHENTICATION_RULE': 'core.auth.user_authentication_rule',


    'AUTH_HEADER_TYPES': ('JWT',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ['http://localhost:80', 'http://localhost:3000',
                         'https://inhouseapp.dataforest.tech', 'http://inhouseapp.dataforest.tech']
CORS_PREFLIGHT_MAX_AGE = 600

ROOT_URLCONF = 'config.urls'
AUTHENTICATION_BACKENDS = [
    'core.auth.CustomModelAuthBackend'
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



# defining file pathes for log handlers
LOG_FILES  = {
#   HANDLER: file path
    "REQUESTS": 'config/logs/REQUESTS/REQUESTS.log',
    "stripe": 'config/logs/stripe/stripe.log'
}
# creating pathes if not exists
for file_path in LOG_FILES.values():
    os.makedirs(os.path.dirname(file_path), exist_ok=True)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{message}',
            'style': '{',
        },
        'full': {
            'format': '%(asctime)s | %(levelname)s line: %(lineno)d || %(message)s',
            'style': '%',
        },
    },
    'handlers': {
        'stripe': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_FILES['stripe'],
            'maxBytes' : 1024*1024*20, # 20MB
            'backupCount' : 7,
            'formatter': 'simple',
        },
        'REQUESTS': {   # handler for middleware logging
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_FILES['REQUESTS'],
            'maxBytes' : 1024*1024*20, # 20MB
            'backupCount' : 7,
            'formatter': 'simple',
        }
    },
    'loggers': {
        'stripe': {
            'handlers': ['stripe'],
            'level': 'INFO',
            'propagate': True,
        },
        'REQUESTS': {
            'handlers': ['REQUESTS'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}



WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'
DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql_psycopg2',
       'NAME': os.environ['DB_NAME'],
       'USER': os.environ['DB_USER'],
       'PASSWORD': os.environ['DB_PASS'],
       'HOST': os.environ['DB_HOST'],
       'PORT': os.environ['DB_PORT'],
       'ATOMIC_REQUESTS': True
   },

}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# supported languages
LANGUAGES = (
    ('en', 'English'),
    ('de', 'German'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('it', 'Italian'),
    ('nl', 'Dutch'),
    ('pt', 'Portuguese'),
    ('ru', 'Russian'),
    ('zh-hans', 'Chinese'),
)
LOCALE_PATHS =[
    BASE_DIR / 'locale'
]
# country detecting by request IP
GEOIP_PATH = BASE_DIR / 'geoip2_country/GeoLite2-Country.mmdb'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = '/api/static/'
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/api/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Emails config
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']


# security settings
if not IS_LOCAL:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

DEFAULT_PASSWORD = os.environ["DEFAULT_PASSWORD"]

FRONT_DOMAIN = os.environ['FRONT_DOMAIN']
API_DOMAIN = os.environ['API_DOMAIN']
# PAYMENTS
STRIPE_PUBLISHABLE_KEY =  os.environ["STRIPE_PUBLISHABLE_KEY"]
STRIPE_SECRET_KEY = os.environ["STRIPE_SECRET_KEY"]
STRIPE_ACCOUNT_ID = os.environ["STRIPE_ACCOUNT_ID"]

# https://inhouseapp.dataforest.tech/onboarding/checkout/payment/result
STRIPE_ORDER_SUCCESS_URL = f'https://{FRONT_DOMAIN}/onboarding/checkout/payment/'
STRIPE_UPDATE_SUCCESS_URL = f'https://{FRONT_DOMAIN}/settings/payment/'

#Hardcoded Stripe account bussiness profile address. In Production - is not used, and data is retrieved directly from STRIPE by STRIPE_ACCOUNT_ID
TEST_BUSSINESS_PROFILE = {"mcc":"5734","name":"InHouse","support_address":{"city":"Kiev","country":"UA","line1":"Solomyanska, 15A","line2":None,"postal_code":"03058","state":"місто Київ"},"support_email":"denis_m@dataforest.ai","support_phone":"+380989592445","support_url":None,"url":"https://inhouseapp.dataforest.tech/"}

FERNET_SECRET_KEY=os.environ['FERNET_SECRET_KEY']   # at first time generate it using. `Fernet.generate_key()`

