"""
Django settings for dropship project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import string
import environ
import os

# Production or Development settings
IS_PRODUCTION = False
IS_LOCAL = True

env = environ.Env()
eviron_filename = '.env_prod' if IS_PRODUCTION else '.env_dev'


environ.Env.read_env(os.path.join(BASE_DIR, 'config', eviron_filename))
ONBOARDING_ENABLED = env('ONBOARDING_ENABLED', cast=bool, default=False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*', 'localhost', 'localhost:8000', '127.0.0.1', '0.0.0.0',]

INTERNAL_IPS = ALLOWED_HOSTS

AUTH_USER_MODEL = 'user.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3th party app
    'modeltranslation',
    'corsheaders',
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_cleanup.apps.CleanupConfig',
    'debug_toolbar',
    'django.contrib.postgres',
    # 'drf_yasg',   # need for swagger ui
    # 'django-storages',    # need for connecting AWS S3 Bucket for static and media files collecting

    # app
    'core',
    'admin_panel',
    'authentication',
    'user',
    'subscription',
    # 'portfolio',
    # 'dashboard',
    # "payments",

]


SOCIAL_AUTH_AUTHENTICATION_BACKENDS = (
    'social_core.backends.apple.AppleIdAuth',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',

    'config.middleware.LangBasedOnUserSettingsMiddleware',   # custom middleware for detecting language from user profile
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'config.middleware.RequestLogMiddleware',

]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'SEARCH_PARAM': 'q',
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'EXCEPTION_HANDLER': 'config.error_handler.rest_framework_custom_exception_handler'
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    'ROTATE_REFRESH_TOKENS': True,

    'AUTH_HEADER_TYPES': ('JWT',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ['http://localhost:80', ]
CORS_PREFLIGHT_MAX_AGE = 600

FRONT_DOMAIN = env('FRONT_DOMAIN')
API_DOMAIN = env('API_DOMAIN')
DEMO_DOMAIN = env('DEMO_DOMAIN')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.app_directories.Loader',
                    ]
                ),
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{message}',
            'style': '{',
        },
        'simple': {
            'format': '{message}',
            'style': '{',
        },
        'full': {
            'format': '%(asctime)s | %(levelname)s line: %(lineno)d || %(message)s',
            'style': '%',
        },
    },
    'handlers': {
        'chargebee': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': f'config/logs/chargebee/chargebee.log',
            'maxBytes' : 1024*1024*20, # 20MB
            'backupCount' : 7,
            'formatter': 'simple',
        },
        'DJANGO': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': f'config/logs/DJANGO/DJANGO.log',
            'maxBytes' : 1024*1024*20, # 20MB
            'backupCount' : 7,
            'formatter': 'simple',
        },
        'REQUESTS': {   # handler for middleware logging
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': f'config/logs/REQUESTS/REQUESTS.log',
            'maxBytes' : 1024*1024*20, # 20MB
            'backupCount' : 7,
            'formatter': 'simple',
        }

    },
    'loggers': {
        'chargebee': {
            'handlers': ['chargebee'],
            'level': 'INFO',
            'propagate': True,
        },
        'DJANGO': {
            'handlers': ['DJANGO'],
            'level': 'INFO',
            'propagate': True,
        },
        'REQUESTS': {
            'handlers': ['REQUESTS'],
            'level': 'DEBUG',
            'propagate': True,
        }


    },
}



WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
DEFAULT_AUTO_FIELD='django.db.models.AutoField'
DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql_psycopg2',
       'NAME': env('DB_NAME'),
       'USER': env('DB_USER'),
       'PASSWORD': env('DB_PASS'),
       'HOST': env('DB_HOST'),
       'PORT': '5432',
       'ATOMIC_REQUESTS': True
   },

}



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LANGUAGES = (
    ('en', 'English'),
    ('ua', 'Ukrainian'),
    ('de', 'German'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('it', 'Italian'),
    ('nl', 'Dutch'),
    ('pt', 'Portuguese'),
    ('ru', 'Russian'),
    ('zh-hans', 'Chinese'),
)
# MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
LOCALE_PATHS =[
    BASE_DIR / 'locale'
]
GEOIP_PATH = BASE_DIR / 'geoip2_country/GeoLite2-Country.mmdb'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/api/static/'
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/api/media/"
MEDIA_ROOT = BASE_DIR / "media"

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')



if not IS_LOCAL:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

DEFAULT_PASSWORD = env("DEFAULT_PASSWORD")


CHARGEBEE_API_KEY = env("CHARGEBEE_API_KEY")
CHARGEBEE_SITE_NAME = env("CHARGEBEE_SITE_NAME")
BLUESNAP_GATEWAY_ID = env("BLUESNAP_GATEWAY_ID")




# AWS_ACCESS_KEY = env('AWS_ACCESS_KEY')
# AWS_SECRET_KEY = env('AWS_SECRET_KEY')
# AWS_REGION = env('AWS_REGION')
# AWS_BUCKET_NAME = env('AWS_BUCKET_NAME')

# # settings for django-storages  # https://django-storages.readthedocs.io/en/latest/
# AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
# AWS_STORAGE_BUCKET_NAME = env('AWS_BUCKET_NAME')
# AWS_S3_SIGNATURE_VERSION = 's3v4'
# AWS_S3_REGION_NAME = env('AWS_REGION')
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = 'public-read'
# AWS_S3_VERIFY = True
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
# AWS_QUERYSTRING_AUTH = False
