# Generated by Django 4.0 on 2025-02-03 15:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailsWhiteList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[("domain", "Domain"), ("full", "Full")],
                        max_length=128,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Emails White List",
                "verbose_name_plural": "Emails White List",
                "ordering": ("-created", "-updated"),
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("value", models.CharField(max_length=128)),
                (
                    "value_type",
                    models.IntegerField(
                        choices=[
                            ("(1, <class 'str'>)", "Text"),
                            ("(2, <class 'int'>)", "Integer number"),
                            ("(3, <class 'float'>)", "Float point number"),
                            ("(4, <class 'datetime.datetime'>)", "Date: YYYY-MM-DD"),
                            ("(5, <class 'datetime.datetime'>)", "Datetime: YYYY-MM-DD HH:MM:SS"),
                        ],
                        default=1,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "verbose_name": "Config variables",
                "verbose_name_plural": "Config variables",
            },
        ),
    ]
