# Generated by Django 5.1.9 on 2026-01-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="value_type",
            field=models.IntegerField(
                choices=[
                    (1, "Text"),
                    (2, "Integer number"),
                    (3, "Float point number"),
                    (4, "Date: YYYY-MM-DD"),
                    (5, "Datetime: YYYY-MM-DD HH:MM:SS"),
                    (6, "Boolean: true or false"),
                ],
                default=1,
            ),
        ),
    ]
