# Generated by Django 4.0 on 2025-02-03 15:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=25, unique=True)),
                ("monthly_price", models.FloatField(default=0.0)),
                ("amount_products_per_week", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=500, null=True)),
                ("is_trial", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=True)),
                ("payment_plan_id", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "ordering": ("monthly_price",),
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("payment_subscription_id", models.CharField(max_length=128, null=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("expire_date", models.DateTimeField(blank=True, null=True)),
                ("next_payment_date", models.DateTimeField(blank=True, null=True)),
                ("paid_amount", models.PositiveIntegerField(null=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Failed"),
                            (1, "Paid"),
                            (2, "Pending"),
                            (3, "Canceled"),
                            (4, "Scheduled"),
                            (5, "Canceling Scheduled"),
                            (6, "Trial"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="plan_subscriptions",
                        to="subscription.plan",
                    ),
                ),
                (
                    "scheduled_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_subscriptions",
                        to="subscription.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ("-created",),
            },
        ),
    ]
