STATUS_FAILED = 0
STATUS_PAID = 1
STATUS_PENDING = 2
STATUS_CANCELED = 3
STATUS_SCHEDULED = 4
STATUS_PAID_CANCELED = 5
STATUS_TRIAL = 6

PAYMENT_STATUSES = (
    (STATUS_FAILED, 'Failed'),
    (STATUS_PAID, 'Paid'),
    (STATUS_PENDING, 'Pending'),
    (STATUS_CANCELED, 'Canceled'),
    (STATUS_SCHEDULED, 'Scheduled'),
    (STATUS_PAID_CANCELED, 'Canceling Scheduled'),
    (STATUS_TRIAL, 'Trial'),
)
