# Generated by Django 4.0 on 2025-02-03 15:06

import uuid

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "User"), (2, "Admin"), (3, "Manager"), (4, "Free access")],
                        default=1,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=124, null=True)),
                ("last_name", models.CharField(max_length=124, null=True)),
                ("avatar", models.FileField(blank=True, null=True, upload_to="avatars")),
                ("email_subscribed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "facebook_user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "apple_user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "google_user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "onboarding_finished",
                    models.BooleanField(
                        default=False,
                        help_text="Flag for defining if user can access site (all sign up steps are finished)",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("pt", "Portuguese"),
                            ("ru", "Russian"),
                            ("zh-hans", "Chinese"),
                        ],
                        default="en",
                        help_text="Field for detecting language for responses",
                        max_length=30,
                    ),
                ),
                (
                    "payment_service_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier of user on PaymentService",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ("-created",),
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("flag", models.FileField(blank=True, null=True, upload_to="country_flags/")),
                ("code", models.CharField(blank=True, max_length=256, null=True)),
                ("state", models.JSONField(blank=True, default=None, null=True)),
                ("country_code", models.CharField(max_length=5, null=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="ConfirmCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("code", models.BigIntegerField()),
                ("expiring_date", models.DateTimeField()),
                (
                    "new_email",
                    models.EmailField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "new_password",
                    models.CharField(blank=True, default=None, max_length=120, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user"),
                ),
            ],
            options={
                "verbose_name": "Confirm code",
                "verbose_name_plural": "Confirm cods",
            },
        ),
        migrations.CreateModel(
            name="CompanyDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("city", models.CharField(db_index=True, max_length=128)),
                ("state", models.CharField(blank=True, max_length=128, null=True)),
                ("postal_code", models.CharField(max_length=16)),
                ("address_line_1", models.CharField(max_length=128)),
                ("address_line_2", models.CharField(blank=True, max_length=128, null=True)),
                ("VAT", models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="user.country",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Company Details",
                "verbose_name_plural": "Users Company Details",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="phone_code",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user_phones",
                to="user.country",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.Permission",
                verbose_name="user permissions",
            ),
        ),
    ]
